### ISSUE TITLE
Feedback & Bug Report

### ISSUE THREAD

**Issue by chullino** [swsnu/swpp2020-team16#103]
버그리포트 작성은 여기서 댓글로 이어가주시면 됩니다.

**Comment by cheezafizz** [comment]
metadata를 설정해서 구글 탭 이름에 react app 대신 service의 이름이 들어가는 것이 좋아 보입니다.

**Comment by cheezafizz** [comment]
들어가자마자 말끔한 ui가 나와서 놀랐는데요!
![image](https://user-images.githubusercontent.com/54826729/101760012-a8fa5300-3b1d-11eb-9226-e868c3fd447f.png)
흰 배경과 회색 배경의 경계부터 글까지 어색한 공간이 남아있는데 이것을 조금 줄이면 더 예쁘게 보일 것 같습니다!

**Comment by wooong210** [comment]
로그인 안 하고 주소창으로 접근 시 이용 가능합니다.

**Comment by wooong210** [comment]
로그인 안 하고 주소창으로 접근 시에 아무 일도 일어나지 않습니다. 다른 동작을 하면 500에러와 리다이렉트 되는 것이 부자연스러워보입니다.

**Comment by chullino** [comment]
> metadata를 설정해서 구글 탭 이름에 react app 대신 service의 이름이 들어가는 것이 좋아 보입니다.

수정해두겠습니다!

**Comment by Namnamseo** [comment]
메인 페이지에서 바로 Test를 눌렀을 때

```
Traceback (most recent call last):
  File ./main.py line 2, in <module>
    from userCode import main
ModuleNotFoundError: userCode
```

이렇게 뜨는 게 맞나요...?

**Comment by ChanwooLucioLee** [comment]
회원가입하면 로그인 안 하고 바로 이용할 수 있었으면 좋겠습니다

**Comment by thdduddn96** [comment]
로그인 시도 시 401 에러가 뜨면서 접속이 안됩니다.

**Comment by cheezafizz** [comment]
Researcher(제 미래입니다)의 입장에서 서비스를 체험해보고 싶은데, permission code를 받을 수 있을까요?

**Comment by jiyewise** [comment]
제가 임의의 코드를 올리면 분석해 주는 사이트라고 알고 있는데, 백준처럼 주어진 문제에 대한 코드만 올릴 수 있는 건가요?
UI가 깔끔하고 user-friendly하다는 인상을 받았는데, 사용법을 익히기가 조금 어려운 것 같습니다

<img width="1152" alt="Screen Shot 2020-12-10 at 7 28 46 PM" src="https://user-images.githubusercontent.com/67668461/101760207-efe84880-3b1d-11eb-82a4-42c0ebc32256.png">

**Comment by chullino** [comment]
> 메인 페이지에서 바로 Test를 눌렀을 때
> 
> ```
> Traceback (most recent call last):
>   File ./main.py line 2, in <module>
>     from userCode import main
> ModuleNotFoundError: userCode
> ```
> 
> 이렇게 뜨는 게 맞나요...?

피드백 감사드립니다. 버그 픽스 해두도록 하겠습니다.

**Comment by HyesunKwak** [comment]
저도 401 에러로 접속이 안됩니다. 로그인이 안되는 이유가 팝업으로 뜨면 좋을 것 같습니다.

**Comment by chullino** [comment]
> 들어가자마자 말끔한 ui가 나와서 놀랐는데요!
> ![image](https://user-images.githubusercontent.com/54826729/101760012-a8fa5300-3b1d-11eb-9226-e868c3fd447f.png)
> 흰 배경과 회색 배경의 경계부터 글까지 어색한 공간이 남아있는데 이것을 조금 줄이면 더 예쁘게 보일 것 같습니다!

메인페이지는 사이트 전체를 설명할 수 있도록 수정해두도록 하겠습니다.

**Comment by wooong210** [comment]
회원가입 시에 409 에러 메시지가 뜨던데, 더 유저 친화적인 에러 메시지가 뜨면 좋을 것 같습니다.

**Comment by ChanwooLucioLee** [comment]
User Friendly VS Machine Efficiency로 나오는데 이 두 개가 꼭 상충되는 것인가요?
Machine Efficiency가 정말로 machine efficiency라면 이건 컴파일러의 역할이고, Time complexity를 뜻한다면 그거랑 user friendly랑 상관없지 않나요?

**Comment by ChanwooLucioLee** [comment]
Rabbit VS Turtle 이게 무슨 말인지 잘 모르겠습니다.

**Comment by cheezafizz** [comment]
비밀번호를 아무렇게나 만들어서 찾으려고 Forget Password를 눌렀는데 메인 페이지로 돌아오기만 하고 아무 일도 일어나지 않습니다. 혹시 어떻게 찾을 수 있을까요?

**Comment by ChanwooLucioLee** [comment]
my/tests/results/ 에서 SHARE!나 EXPLORE! 버튼 눌렀을 시 아무 반응이 없습니다.

**Comment by cheezafizz** [comment]
같은 이메일로 여러개의 username을 가진 복수의 아이디를 만들 수 있는 것 같은데 혹시 이것은 의도된 것인가요?

**Comment by SPICYJO** [comment]
Bar chart (user friendly vs machine efficency , turtle vs rabbit, ...)에 마우스를 hover했을 때 세부내용이 나오는데 필요없는 내용(1이라는 숫자)이 나오는 것 같아요!

**Comment by jiyewise** [comment]
제가 coder로 가입했지만 manager로 변경하고 싶은데, 자신의 status를 변경할 수 있는 기능이 있나요?

**Comment by ddongminstar** [comment]
> User Friendly VS Machine Efficiency로 나오는데 이 두 개가 꼭 상충되는 것인가요?
> Machine Efficiency가 정말로 machine efficiency라면 이건 컴파일러의 역할이고, Time complexity를 뜻한다면 그거랑 user friendly랑 상관없지 않나요?

Time Complexity와는 별개로, 일반적으로 코드를 직관적으로 짜는지, 속도를 신경 쓰는지만 고려했습니다. 
가령 list를 쓰는지, map을 쓰는지 등으로요.

**Comment by jaewooklee93** [comment]
singup 이후에 singin에 자동완성되는 것이 username이 아니라 email이 되어서 로그인을 바로 하기가 어려운 것 같습니다

**Comment by lgm0905** [comment]
1. 메인페이지에서 오른쪽 체크버튼은 100%일때 색이 채워지는 것인가요?
2. 처음 튜토리얼로 3개 문제를 proceed한 후, home에서 첫번째 문제를 풀고 proceed를 해도 다음 문제로 넘어가지 않습니다.

**Comment by ChanwooLucioLee** [comment]
Invitations이 기본으로 Accept로 되어 있습니다. 수락하기 전에는 Pending 등과 같이 떠야되지 않을까요

**Comment by SPICYJO** [comment]
Bar chart 레이블에 클릭하면 (e.g. rabbit을 클릭) 그 요소가 빼지는데 클릭이 안되게 해야할 것 같아요!

**Comment by jiyewise** [comment]
invitation에서 accept를 눌렀는데 my group에 들어가면 아무 그룹도 없다고 뜹니다..!

**Comment by ChanwooLucioLee** [comment]
My Messages 들어가면 404 not yet implemented가 뜹니다

**Comment by kwonsunbin** [comment]
> Rabbit VS Turtle 이게 무슨 말인지 잘 모르겠습니다.

주어진 문제를 문제에서 요구하는 방식 대로 정직하게 푼다면 turtle인 것이고, 그렇지 않고 다른 꾀를 사용하여 해결한다면 Rabbit이라는 의미입니다!

**Comment by songbird39** [comment]
MBTI에서 각 속성을 설명해주듯이, 결과페이지에서 자신의 결과와 함께 이게 어떤 걸 의미하는지를 알려줬으면 좋겠습니다! 개인화된 해석결과여도 되고... 전반적인 설명이어도 괜찮을 것 같고요

**Comment by cheezafizz** [comment]
앞서 제기된 문제랑 같은 맥락인 것 같은데, username이 같은 계정이 일단은 아무 에러없이 만들어지는데, 실제로는 중복된 username가 있으면 입력된 정보대로 계정이 생성되지 않습니다.

**Comment by jaewooklee93** [comment]
저는 아직 로그인을 못하고 있습니다 ㅠㅠ 아래에 Toast처럼 request 401 에러 이런게 나오는데 잘 안보이는 곳에서 있어서 에러가 나는줄 몰랐네요

**Comment by wooong210** [comment]
아무것도 안 치고 넘겼는데 carefully typed 가 99%로 뜹니다.

**Comment by cheezafizz** [comment]
> 저는 아직 로그인을 못하고 있습니다 ㅠㅠ 아래에 Toast처럼 request 401 에러 이런게 나오는데 잘 안보이는 곳에서 있어서 에러가 나는줄 몰랐네요

저같은 경우에는 다른 분의 username과 같아서 안 된 거였습니다. 괴상한 아이디와 이메일을 입력해보세요

**Comment by songbird39** [comment]
반대 성향 보기 버튼이었나? https://codingmbti-dev.shop/relation/ 페이지가 비어있습니다.
![image](https://user-images.githubusercontent.com/50364722/101761142-24a8cf80-3b1f-11eb-8ddd-179767b96a15.png)

**Comment by lgm0905** [comment]
MBTI 에 어떤 종류들이 있는지 따로 페이지를 만들거나 해서 알수있으면 재미있을 것 같습니다 ㅎㅎ

**Comment by songbird39** [comment]
테스트를 이미 했음에도 홈으로 돌아가면 다시 테스트가 뜨네요. 차라리 결과창으로 리다이렉트되면 좋을 것 같아요.

**Comment by cheezafizz** [comment]
ide가 되게 예쁜데
![image](https://user-images.githubusercontent.com/54826729/101761230-3a1df980-3b1f-11eb-8e4a-e28f0eb12ff0.png)
현재줄을 annotate하는 것이 오른쪽 창까지 넘어가서 살짝 거슬리는 감이 없잖아 있는 것 같습니다!

**Comment by jaewooklee93** [comment]
user friendly vs machine friendly는 대구가 안 맞는 것 같습니다. human friendly가 어떨까요?

just typed도 콩글리시로는 이해가 되는데 좀더 멋진 표현이 있을 것 같습니다

time complexity vs intuitive code의 경우에는 맨 첫번째의 user vs machine과 상당히 유사한 개념이 아닐까 싶습니다

**Comment by wooong210** [comment]
extension을 추가할 수 있으면 더 좋을 것 같습니다.

**Comment by hhjjpp** [comment]
test 문제 전부 그냥 넘겼는데 carefully typed 가 나옵니다.!
analysis report 페이지 하단 explore 버튼은 무엇을 하는 버튼인가요?
유형별로 캐릭터 설정해두신 거 친근하게 느껴져서 좋았습니다!

**Comment by Jeseong-Jeong** [comment]
어떤 test case에 의해 실패했는지 나오면 좋을 것 같습니다....
coding mbti라기보단 코딩 문제 사이트로 보여요
