### ISSUE TITLE
bug: Dockerfile, Docker compose scripts won't work as expected

### ISSUE THREAD

**Issue by ddongminstar** [swsnu/swpp2020-team16#30]
**Describe the bug**
1. Dockerfile need to install libpq-dev, python3-dev and other essential files with apt install -y ...
2. Docker compose environment have to be exported with DJANGO_MODULES_SETTINGS to resolve our django shell
3. little typo relate to #29 
4. Update requirements with our new files

**Screenshots**
Too many errors, just fix with new codes.

**Additional context**
Current solution requires too many time for build docker image. Run apt update and apt-install update everytime is really burden and costly. Consider build a new base image with installed psycopg2 connection.

**Comment by chullino** [comment]
Describe the bug (2)  
 - dev에 오늘 가장 마지막으로 푸시한 것에서도 문제가 발생하는지 궁금합니다. 

Describe the bug (4)
 - requirements.txt는 현재로서는 최신화되어 있는 상황입니다만,  requirements.txt를 말씀하신 것인지 궁금합니다.

추가로, `Consider build a new base image with installed psycopg2 connection.` 이것은 제가 찾아볼게요. 일이 많아 듀가 불분명하긴 합니다만 이렇게 바꿔두는 게 좋겠어요.
