### ISSUE TITLE
Feat : Coder는 로컬 환경에서 코드 문제를 풀고 curl을 날릴 수 있어야 한다.

### ISSUE THREAD

**Issue by chullino** [swsnu/swpp2020-team16#69]
**Is your feature request related to a problem? Please describe.**

Coder는 로컬한 환경에서 코드 문제를 풀고 curl을 날릴 수 있어야 하고,
서버는 해당 코더에게 코드 문제에 대한 답이 맞는지 확인해주고, 
서버는 해당 코더에게 분석 결과를 제공해줄 수 있어야 한다.

**Describe the solution you'd like**
API를 하나 뚫어주어야 한다.
response를 설정해야 한다. (어떤 데이터를 리스폰스로 넘겨줄 것인지)

**Comment by ddongminstar** [comment]
curl를 뚫어줄 필요는 없는거 같아요. 지금 개발 방향과 완전히 다르고, 큰 의미가 없어보입니다.

**Comment by chullino** [comment]
이게 교수님이 피드백 사항인데, 대안을 생각해볼 필요가 있을 듯 싶어요. 저도 문제 단위로 애널리시스를 내어주는 것은 무의미하다고 생각합니다만, 교수님께서는 아마 브라우저 IDE 사용 없이 로컬 환경에서 개발해서 직접 데이터를 업로드할 수 있는 상황을 가정하신 것으로 보입니다.
