### ISSUE TITLE
Current Implementation in Home with fixed problem_id will crash

### ISSUE THREAD

**Issue by ddongminstar** [swsnu/swpp2020-team16#79]
**Describe the bug**
Current implementation will crash if problem of problem_id is None.

**Additional context**
Need some change like request list of problems with fixed_size(less than 5) and pick randomly one problem in front-end or add some views to retrieve random available problem.

**Comment by chullino** [comment]
혹시 이 문제는 데이터베이스에 id가 increment하는 상황 때문에 발생하는 문제 아닌가요? 비슷한 문제를 마주했었어서요.
