### ISSUE TITLE
Feat : Add and Fix models for UM, TI, EF, JC

### ISSUE THREAD

**Issue by kwonsunbin** [swsnu/swpp2020-team16#87]
User Friendly - Machine Efficiency
Time Complexity - Intuitive Code
Easy style - Formatted Style 
Just type - Carefully type

조금 더 뚜렷한 결과를 보여주기 위해서 위의 4가지 기준을 조금 수정하면 어떨까 제안해 봅니다. 현재 4가지 중 2가지만 어느정도 되어있는 상황이라 바꾸는데 큰 어려움을 없을 것 같습니다.

### 그대로 진행 with ITP1_6_B
총 4가지 기준 중 User Friendly - Machine Efficiency에 해당하는 "ITP1_6_B"만 그나마 완성에 가깝다 생각됩니다!

### 그대로 진행 with 모든 문제
erase_cnt와 elapsed time 의 경우는 모든 문제에서 받아올 수 있으므로 Just Type과 Carefully Type을 구분하는 데이터로 사용하면 사실 ML 모델 없이도 일정 기준 이상 이하로 classify 해도 될 것 같습니다.

###  변경 Rabbit - Turtle ? 적당한 이름 찾기
파이썬 언어의 특성상 indent가 강제되고 {}를 사용하지 않는 등 스타일을 구별짓기 어려우므로! 

"ITP2_3_B" - min, max 구현하기 문제의 solution 데이터들을 봤을 때 
1. 직접 min, max를 구현한 사람
2. python 자체에서 제공하는 min, max를 가져다 쓴 사람
두 부류로 나뉘는 것을 보아 꾀부리는 사람, 정직한(?) 사람 이렇게 구분해보면 재밌을 것 같습니다.

### 그대로 진행 - 새 문제 찾기
비슷한 비율로 1:1로 binary class로 잘 나누어질만한 새로운 문제를 찾는 것이 관건일 듯 합니다

@ddongminstar

**Comment by chullino** [comment]
Rabbit - Turtle 이거 좋네요 =)
그리고 시험 끝나구서 여기 문제 처리 관련해서 저 한번만 설명 부탁드려요. 저도 제가 처리해야할 작업이 상당 부분 완료된지라, 그 다음 스프린트할 때 제공할 문제 수를 좀 더 늘릴 때 문제 몇 개 좀 더 처리해보도록 할게요!
