### ISSUE TITLE
Feat : resolve hard codings in Backend analysis app

### ISSUE THREAD

**Issue by kwonsunbin** [swsnu/swpp2020-team16#88]
현재 ITP1_6_B와 ITP2_3_B에 해당하는 솔루션이나 레포트를 가져올 때 하드 코딩 방식으로 가져오는데,

다양한 문제 추가 이후 

backend/test_cases의 폴더 디렉터리를 이용하여 hard coding을 resolve 해야함

**Comment by chullino** [comment]
아마, 이 하드코딩 관련 문제가 언제 발생하는 듯 싶냐면, 백엔드 데이터베이스가 id를 incrementing하게 가져가는 거 때문에 발생하는 듯 싶어요. 그래서 id를 28,29,30 으로 짓게 되는데요. 이 문제는 가능하면 이번 스프린트에서 처리해두면 좋겠네요!

**Comment by chullino** [comment]
database를 매번 플러시해서 언제나 기대되는 데이터를 만들 수 있도록 database-init.sh 파일 만들어둘게요.
