### ISSUE TITLE
Fix: Backend test coverage too low.

### ISSUE THREAD

**Issue by chullino** [swsnu/swpp2020-team16#92]
**Is your feature request related to a problem? Please describe.**

analysis.model, analysis.view test coverage should be resolved.

<img width="774" alt="스크린샷 2020-11-24 오후 8 13 56" src="https://user-images.githubusercontent.com/40787830/100087207-b4008280-2e91-11eb-9c72-a70cdc15050a.png">

**Comment by kwonsunbin** [comment]
처리했습니다!
